### ISSUE TITLE
MSVC: compile error

### ISSUE THREAD

**Issue by duzenko** [shff/opengl_sky#3]
```
1>------ Build started: Project: ncnc, Configuration: Debug Win32 ------
1>main.c
1>C:\Users\a\source\repos\opengl_sky\main.c(183,40): error C2054: expected '(' to follow 'packed'
1>C:\Users\a\source\repos\opengl_sky\main.c(242,24): error C2057: expected constant expression
1>C:\Users\a\source\repos\opengl_sky\main.c(242,24): error C2466: cannot allocate an array of constant size 0
1>C:\Users\a\source\repos\opengl_sky\main.c(242,25): error C2133: 'error_log': unknown size
...
```

![image](https://user-images.githubusercontent.com/1481807/86631142-6fee0d80-bfd6-11ea-8be4-7844b99545c7.png)

**Comment by shff** [comment]
@duzenko well, it uses modern C features which MSVC doesn't have.

It should be possible to remove those features and use something more portable, though! Unfortunately I don't have a Windows machine! Why don't you give it a go? 😉

**Comment by duzenko** [comment]
> 
> 
> @duzenko well, it uses modern C features which MSVC doesn't have.
> 
> It should be possible to remove those features and use something more portable, though! Unfortunately I don't have a Windows machine! Why don't you give it a go? 😉

I did it in my fork, but it's a radical overhaul rather than a minor compiler compatibility fix.

**Comment by shff** [comment]
@duzenko Glad you got it working!
